### ISSUE TITLE
HMRC-regional-trade-statistics

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#12]

**Comment by ajtucker** [comment]
- [ ] Output metadata to `observations.csv-metadata.trig`
- [ ] Create CSVWMetadata from local repo: `CSVWMetadata('https://gss-cogs.github.io/family-trade/reference/')`

**Comment by VTula2000** [comment]
30M Triples pipeline breaks

**Comment by RedWalters** [comment]
- [x] **Does the dataset show up or is there an error?**
Yes
PMD4 : http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc_rts-catalog-entry

PMD3: http://gss-data.org.uk/dataset?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc_rts

- [x] **Is it in the list of datasets from the main page?**
- [x] **Is there descriptive metadata on the search page?**
On PMD3 yes, on PMD4 no. Only Title shown. Since it shows on PMD3 this is most likely an issue on Swirrls side, 
possible due to the size of the dataset and the methods in which it was pushed through.


- [x] **Does transformed info match the original?**
Yes - The original data is in txt form so little transformation work is needed, which reduces the risk of data loss or change.

- [] **Does the tidydata download show all the data?**
No, PMD3 seem to fail everytime the download is attempted. With PMD4 the download works (after a time) but only returns 4mil out of the 4.8m results.

- [x] **Note differences in column/row headers**
The original data has no column headers, as such the column headers were taken from a datapack on the HMRC RTS page.


- [x] **Are there multiple cubes? List titles of cubes**
N/A : One cube. 

- [x] **What needs differentiating? Totals**
N/A

- [x] **Are there titles that need harmonising? World/Worldwide**
N/A

- [x] **Does the structure look sensible?**
Yes. 
- [x] **Does the hierarchy work?**
Yes. 
- [x] **What needs further investigation or context?**
N/A
- [x] **Any duplications?**
No.
- [x] **List any detailed metadata/methodology to add retrospectively**
HMRC Partner Geography codes have been taken from either the Codseq or Codalpha columns depending on whether Codseq begins with '#'

- [x] **Short metadata added**
N/A

**Comments:**

Seems as though the only issues on this are Swirrl side, and most likely due to the size of the data set.

Only other real thing to note here is that some of the transform is hard coded (such as the download link to the specific files) which could cause issues if they make any changes.
Also to note the information for the column headers and txt file contents is found here:
https://www.uktradeinfo.com/Statistics/RTS/Documents/RTS%20Detailed%20data%20information%20pack.pdf

**Comment by RedWalters** [comment]
Issue created for aforementioned PMD issues: #Swirrl/ons-data-export#19

**Comment by JasonHowell** [comment]
@RedWalters   looking at Alex's dataset tracker the transformation is in "unstable" status.  Jenkins is clearly showing subsequent failures in runs: https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC_RTS/60/

Are there further changes in the pipeline or is this in a steady state?

Thanks
Jason.

**Comment by JasonHowell** [comment]
BA's confirming that it looks sensible at the moment.   It's okay to go out with the closed period but need to look at the open period when the new data set is available.

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.

**Comment by canwaf** [comment]
This dataset is primed for a change to API/OData-based conversion into tidy data. The new source would be https://api.uktradeinfo.com/RTS. An example is already ready but needs work with a Business Analyst to update relevant json files at https://github.com/GSS-Cogs/family-trade/compare/canwaf/issue12#diff-434ac3548a86af9757ae14cb6b6b5ea80cbe22c139e4e7b5def50117d361b122

**Comment by canwaf** [comment]
This dataset is primed for a change to API/OData-based conversion into tidy data. The new source would be https://api.uktradeinfo.com/RTS.

**Comment by canwaf** [comment]
This is blocked pending the release of the API Download functionality to gss-utils.

**Comment by canwaf** [comment]
Handing this over to @Shannon95 to test the instructions on how to use the new API functionality in gss-utils. I've pushed the info.json updates to master.

**Comment by canwaf** [comment]
Hey @rossbowen, what needs next doing with this? I haven't seen any other commits on the branch.

**Comment by rossbowen** [comment]
Some notes here for additional manipulation:

I think drop everything except:

## `Measure Type`:
- Pivot Value/Net Mass into a singular column which contains either the string `value` or the string `net-mass`.

## `Value`:
- The numeric column associated to `Value` / `Net Mass`.

## `Flow Type`:

- Rename `FlowTypeDescription`
- `pathify()`

## `UK Region`
- Take `RegionName` and map to statistical geography codes.

Fully specify the URL in the dataset. e.g.,

`http://statistics.data.gov.uk/id/statistical-geography/{code}`.

This SPARQL query will get the codes from the stats geography site.

```
SELECT ?s ?o
WHERE {
  ?s ?p <http://statistics.data.gov.uk/def/geography/collection/E12> .
  ?s <http://statistics.data.gov.uk/def/statistical-geography#officialname> ?o .
}
```
- NI `N92000002`
- Wales `W92000004`
- Scotland `S92000003`

There are two entries with anomalies:

Unallocated - Known
Unallocated - Unknown

For these, pathify them and and return the URIs:

`http://gss-data.org.uk/data/gss_data/trade/HMRC_RTS#concept/uk-region/unallocated-known`
`http://gss-data.org.uk/data/gss_data/trade/HMRC_RTS#concept/uk-region/unallocated-unknown`

Could the DE please also return a `.csv` of the entries in this column so this could be turned into a codelist.

## `Country`

Take `CountryCodeAlpha`.
Return `http://gss-data.org.uk/def/trade/concept/international-country-codes/{CountryCodeAlpha}`.

Where there isn't one, take `pathify(CountryName)` and return:
``http://gss-data.org.uk/data/gss_data/trade/HMRC_RTS#concept/country/{CountryName}`.

Could the DE please also return a `.csv` of the entries in this column so this could be turned into a codelist. Would be handy to have the Country Names alongside those in the `.csv` for the codelist but not the main tidy data file.

## `SITC Code`
Concat `Sitc1Code` and `Sitc2Code`.

**Comment by canwaf** [comment]
Added new key (which is just checked for presence, not specific value) at `load.accretiveUpload` to `info.json`. More work required, working on branch/offline until its done.

**Comment by canwaf** [comment]
* DM please confirm my interpretation that the quarter values here are calendar quarters and not government quarters
* HMRC_RTS_Country_codelist.csv and HMRC_RTS_Region_codelist.csv created as requested

**Comment by canwaf** [comment]
The SPARQL test failures are now over to a Data Manager to sort I believe. https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC_RTS/63/testReport/. Paging @rossbowen.

**Comment by canwaf** [comment]
I've got a fresh failure for you, @rossbowen https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC_RTS/66.

**Comment by rossbowen** [comment]
Cannot pass IC-16 without hitting `503` errors.
https://ci.floop.org.uk/job/GSS_data/job/Trade/job/HMRC-regional-trade-statistics/73/testReport/

**Comment by ajtucker** [comment]
> Cannot pass IC-16 without hitting `503` errors.

There's a distinction between errors and failures. An IC fails if the data is invalid wrt. the test. The IC will error if there's an unexpected issue where the test result can't be determined. In this case, the 503 is an error.

We have a switch we could toggle to say "allow errors" and this would mean that the build would ultimately pass, though with a yellow warning sign.

As it stands, even though this build hasn't passed, the draft is still available for publishing if the reviewer wants to.

**Comment by canwaf** [comment]
- [ ] Refactor to change download behaviour to start at max available date and work backwards.

**Comment by canwaf** [comment]
Data published and available on staging.

**Comment by JasonHowell** [comment]
This available on Staging and currently being loaded onto BETA.  It's a very large dataset.

**Comment by Shannon95** [comment]
Loaded onto beta [here](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-regional-trade-statistics-catalog-entry)
