### ISSUE TITLE
Regional Trade Statistics - Publisher Feedback

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/family-trade#238]
From the review held on the 11th August with Maxim Mastrangelo this is the feedback:

RTS 
-	Region is a numeric code rather than the alpha. e.g. it says W92000004 rather than Wales etc.
-	Seems to only have Q1 2021 is this intentional as it is just testing? Also, it appears you cannot filter on period, probably for this reason that there’s only 1 quarter of data available?
-	SITC4 column header should be renamed to ‘SITC’ maybe. RTS only goes to SITC 2 detail but has SITC 1 and 2 breakdowns.
-	SITC descriptions could include the numeric code alongside the alpha description. E.g. rather than just saying ‘Beverages’ it could say ’11 Beverages’ or have ‘11’ in an adjacent column.
-	Description can be found on the following page under ‘details’: https://www.gov.uk/government/statistics/uk-regional-trade-in-goods-statistics-first-quarter-2021

Now need to assess what is can be done.

**Comment by JasonHowell** [comment]
Need to progress the feedback from the QA comments above.

**Comment by Shannon95** [comment]
Updates implemented inline with publisher feedback as follows :

[Beta](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-regional-trade-statistics-catalog-entry) 
[Staging](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-regional-trade-statistics-catalog-entry)

**The region is a numeric code rather than the alpha. e.g. it says W92000004 rather than Wales etc.**
The name is held behind the code and once on the filer shows Wales etc.

**Seems to only have Q1 2021 is this intentional as it is just testing? Also, it appears you cannot filter on period, probably for this reason that there’s only 1 quarter of data available?**
This was due to the fact that all of the data wasn't loaded onto the beta site at the time of QA with the publisher. All data is now available. 

**SITC4 column header should be renamed to ‘SITC Code’ maybe. RTS only goes to SITC 2 detail but has SITC 1 and 2 breakdowns.**
The column has been renamed. 

**SITC descriptions could include the numeric code alongside the alpha description. E.g. rather than just saying ‘Beverages’ it could say ’11 Beverages’ or have ‘11’ in an adjacent column.**
The codes are linked to the labels. 

**Description can be found on the following page under ‘details’: https://www.gov.uk/government/statistics/uk-regional-trade-in-goods-statistics-first-quarter-2021**
The description has been updated.

**Comment by TahaRana97** [comment]
Reviewed by Rob 19/01/22 and all good - can be closed
