### ISSUE TITLE
RTS interactive analysis - Publisher Feedback

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/family-trade#239]
After the review with Maxim Mastrangelo on 11th August, feedback comments:

RTS interactive analysis
-	Could rename this ‘RTS business counts’
-	Can’t seem to filter on period despite it including some quarterly and some annual data
-	Description can be taken from here: https://www.gov.uk/government/statistical-data-sets/regional-trade-statistics-interactive-analysis-first-quarter-2020

Just need to understand what can be actioned.

**Comment by Shannon95** [comment]
Data has been updated in line with QA feedback. 
[Staging](https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-regional-trade-statistics-interactive-analysis-catalog-entry&apply-filters=false)
[Beta](https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-regional-trade-statistics-interactive-analysis-catalog-entry)

RTS interactive analysis QA Feedback. 

**Could rename this ‘RTS business counts’**
done 

**Description can be taken from here: https://www.gov.uk/government/statistical-data-sets/regional-trade-statistics-interactive-analysis-first-quarter-2020**
Done

**Can’t seem to filter on period despite it including some quarterly and some annual data**
Due to the size of this dataset, this functionality is cannot be implemented because the dataset is too large to generate a period codelist This is a known issue here.

**Comment by TahaRana97** [comment]
Reviewed by Rob 19/01/22 and all good - can be closed
