### ISSUE TITLE
QA Feedback - Trade in goods: all countries, seasonally adjusted - 30/09/2021

### ISSUE THREAD

**Issue by JasonHowell** [GSS-Cogs/family-trade#262]
Held a QA session with Sarah Whiting and Marc John.  Trade in goods: all countries, seasonally adjusted
https://beta.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-sa-trade-in-goods-catalog-entry

Observations were:
They have country codes in publication, does the code need to be added?
Check the observation status column?

**Comment by Shannon95** [comment]
Dataset has been updated with the latest publication. (note next release is due 11th November, CRON job is scheduled to pick this up. 


Regarding QA feedback comments from the publisher: 
**They have country codes in publication, does the code need to be added?**

We take the country code as the _notation_  and form the _label_  of the full country name from this, which is then presented on pmd. They are representing the same thing e.g. ![image.png](https://images.zenhubusercontent.com/5d9ef400cec9b500015b5dc8/e88f7cdc-305a-4977-bc23-c029152f823a)

**Check the observation status column?**
Some data for countries have been marked with N/A. This is because Trade in Goods do not collate data from these countries. 

This information has been taken from the source data footnotes and has been added to the Description within the 'about' section on pmd. 

Where this applies the value will be blank and the Observation status column will be populated with  _Not Applicable_ 


![image.png](https://images.zenhubusercontent.com/5d9ef400cec9b500015b5dc8/f6ea8be0-97d7-4650-ac3b-a35d2eca80da)

**Comment by Shannon95** [comment]
@JasonHowell QA comments have been covered and once given the once over I believe this issue can be closed.

**Comment by TahaRana97** [comment]
Reviewed by Rob 19/01/22 and all good - can be closed
