### ISSUE TITLE
UK trade in services: service type by partner country, non-seasonally adjusted #17

### ISSUE THREAD

**Issue by MartynBSpooner** [GSS-Cogs/family-trade#60]

**Comment by mikeAdamss** [comment]
- [ ] Does the dataset show up or is there an error?
- [ ] Is it in the list of datasets from the main page?
- [ ] Is there descriptive metadata on the search page?
- [ ] Does transformed info match the original?
- [ ] Does the tidydata download show all the data?
- [ ] Note differences in column/row headers
- [ ] Are there multiple cubes? List titles of cubes 
- [ ] What needs differentiating? Totals - Nothing
- [ ] Are there titles that need harmonising? World/Worldwide 
- [ ] Does the structure look sensible? 
- [ ] Does the hierarchy work?
- [ ] What needs further investigation or context? 
- [ ] Any duplications?
- [ ] List any detailed metadata/methodology to add retrospectively 
- [ ] Short metadata added

**Comment by mikeAdamss** [comment]
@JasonHowell - needs a BA review. 

There is a question around product dimension filtering but that is being addressed at a global level (i.e "Product" is a mess overall, Alex is looking at it). Beyond that the pmd4 dataset looks sensible to me.

Note - the label for "Flow" is a bit off on the pmd3 version, thats because of a duplicate label that's not been fixed on pmd3 yet (because we don't care about pmd3 - pmd4 is fine).

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.
