### ISSUE TITLE
ONS-GDP-at-current-prices-real-time-database-YBHA

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#7]
https://github.com/GSS-Cogs/family-trade/tree/master/datasets/ONS-GDP-at-current-prices-real-time-database-YBHA

**Comment by Grace-W** [comment]
Ref_period notes for decision made on labels: http://www.oecd.org/sdd/40315408.pdf

**Comment by mikeAdamss** [comment]
- [] Does the dataset show up or is there an error?
- [] Is it in the list of datasets from the main page? 
- [] Is there descriptive metadata on the search page? 
- [] Does transformed info match the original? 
- [] Does the tidydata download show all the data? 
- [] Note differences in column/row headers
- [] Are there multiple cubes? List titles of cubes
- [] What needs differentiating? Totals
- [] Are there titles that need harmonising? World/Worldwide 
- [ ] Does the structure look sensible?
- [ ] Does the hierarchy work? 
- [ ] What needs further investigation or context? 
- [ ] Any duplications? 
- [ ] List any detailed metadata/methodology to add retrospectively
- [ ] Short metadata added

**Comment by IeuanMan** [comment]
@Rob T 

https://docs.google.com/document/d/1MqKTtaMoPv9GvQ2ifeZOZzHi4eTWUW4GU5n9va6WHy4/edit

BA Quality Assurance High Level Checks 
Dataset: GDP at current prices – real-time database (YBHA)
Done by:Rob Thomlinson
Date:07-04-20
PMD V4
Is the dataset listed  in PMD v4 staging?
No
Does the dataset open?


Is there descriptive metadata on the PMD v4 staging landing page?


Does transformed info seem to match the original?


Contents Modified Date


PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Basic
Modified Date
27 Mar 2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
Yes
Does the structure look sensible?
Yes

Overview
General comments on the dataset
This dataset is now out of date.  This was published again 31st March
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data
Possibly need to think about the measure being GBP Million, Current prices rather than just GBP Million.  The Current Prices element is at least as important.as the Seasonal Adjustment
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?
Should we have Seasonal Adjustment as a dimension? The dataset is all seasonally adjusted.  Should be consistent across datasets.
GDP Vintage and GDP Publication don’t feel right as titles giving obviously what they are.  I think we could simplify them to GDP date / period and GDP Publication date
GDP Estimate Type isn’t quite right either...the Quarterly National Accounts are a publication, not an estimate.  GDP Publication Type I think would work better.
Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?
Scales, decimal points, values etc look to be fine

**Comment by rob** [comment]
Thanks

**Comment by mikeAdamss** [comment]
`
Expected empty result set, got:
code
http://reference.data.gov.uk/id/gregorian-interval/2020-03-01T00:00:00/P3M
`
We're missing 2020 gregorian dates in the time reference pipeline. Not much we can do until that's addressed.

**Comment by mikeAdamss** [comment]
have put review questions in bold, could do with a decision.

**Comment by RobThomlinson** [comment]
I've had a response from the data producers about this one (ONS GDP)

To summarise the dimensions from the spreadsheet:
- The top row should be called "Estimate Type" (1st, QNA, M1, M2)
- the row below should be called "Publication Date" or "Date of Publication".  Use of the ISO date period is OK, but may be mislerading.  We could get actual publication dates back to 2016 fairly easily (ONS Publication Calendar), but no way before that, but may also be unclear to users what it means.  Metadata would be needed to make it clear
- The first column is "Reference Period".  Any dates or date range applied to interpret this in ISO woud be an arbitrary decision.  Changing from "2015 Q1" would need metadata explaining.

**Comment by mikeAdamss** [comment]
Have updated to "Publication Date" and "GBP Estimate Type" in line with the above (had to add the BGP to "Estimate Type" as the namespace for "Estimate Type" is already taken - we may be able to change this in time).

**Comment by mikeAdamss** [comment]
Done and BA's are happy. Just not on pmd4 yet (have raised).

**Comment by JasonHowell** [comment]
Thanks all.  Great work.  Chatting with Swirrl on how best to progress uploads to PMDv4 without re-introducing data issues already been fixed.

**Comment by mikeAdamss** [comment]
where this was raised: https://github.com/Swirrl/ons-data-export/issues/17

**Comment by JasonHowell** [comment]
This is now on PMDv4.  BA's to review.

**Comment by JasonHowell** [comment]
Latest version on PMDv4.  BA's to review.

**Comment by JasonHowell** [comment]
BA's reviewed and good to go.

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.

**Comment by rossbowen** [comment]
Ready for review at https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-gdp-at-current-prices-real-time-database-ybha-catalog-entry&filters-drawer=open.

**Comment by Tracey-B** [comment]
@rossbowen BA checks completed, transformation appears, subject to the following comments for consideration:

- Only able to filter for GDP Estimate Type
- Does Reference Period and Estimate Type need to be prefixed with GDP?
- The dataset states that the figures are seasonaly adjusted however I cannot see that information on PMD, does this need to be included?

-

**Comment by JasonHowell** [comment]
This datasets has been reviewed by the publisher (Andrew) 30/07/2021 and given approval.  
This issue can now be closed.
