### ISSUE TITLE
ONS-Regional-gross-domestic-product-city-regions

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#79]
https://github.com/GSS-Cogs/family-trade/tree/master/datasets/ONS-Regional-gross-domestic-product-city-regions

**Comment by LPerryman** [comment]
Can be joined with transform https://github.com/GSS-Cogs/family-trade/issues/81

**Comment by Shannon95** [comment]
Available on PMD4 as a draft set to claim (contains data joined together from both #79 and #81), under GSS_data/Trade/ONS-Regional-gross-domestic-product-city-regions. Contains 8 cubes due to there being multiple measures. 
Things to note: 
- Reference data needs to be fixed up as some dimensions are appearing as URL's.
- I had issues with duplicates and had to drop some data to solve the issue. Sheets named:'Table 6', 'Table 7', 'Table 11', 'Table 12'  and 'Table 13' within source: https://www.ons.gov.uk/economy/grossdomesticproductgdp/datasets/regionalgrossdomesticproductenterpriseregions
rows 256 and 373 have the same dimensions outputs: Cherwell, E07000177, LA, whatever year (expect the value of course) therefore not enough to differentiate them and no other dimensions available to do so. 
I assume the area name Cherwell should not appear twice? might be something to go back to the publisher for clarification. For now, I have dropped the row 373 from associated sheets to pass the error.

**Comment by rossbowen** [comment]
Just had a look over - I think it works as is but I think this is a really good candidate to think about how we do harmonisation.

In particular, instead of defining a separate codelist for `area-name`, I think I'd like to see defined a codelist for `city-regions` (since these are new concepts not really defined anywhere), and to use the statistical geography codes where we can. That way we define the concept which isn't defined elsewhere - because we have to! But then make that link to geographies which are defined elsewhere.

So a `city-region` codelist which ends up looking something like this (albeit with full URIs) might be cool:

e.g.

Na h-Eileanan Siar (`S12000013`), Orkney Islands (`S12000023`), Shetland Islands (`S12000027`) are part of the Scottish Island Councils (`scottish-island-councils`).

```turtle
@prefix gss-scheme: <http://gss-data.org.uk/def/trade/concept-scheme/>
@prefix city-region: <http://gss-data.org.uk/def/trade/concept-scheme/city-region>
@prefix pmdcat: <http://publishmydata.com/pmdcat#>
@prefix skos: <http://www.w3.org/2004/02/skos/core#>
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
@prefix statistical-geography: <http://statistics.data.gov.uk/id/statistical-geography/>

gss-scheme:city-region a pmdcat:ConceptScheme, skos:ConceptScheme ;
  skos:hasTopConcept city-region:scottish-island-councils, ... ;
  .

city-region:scottish-island-councils a skos:Concept ;
  skos:narrower statistical-geography:S12000013, statistical-geography:S12000023, statistical-geography:S12000027 ;
  rdfs:label "Scottish Island Councils" ;
  .

statistical-geography:S12000013 a skos:Concept ;
  skos:broader city-region:scottish-island-councils ;
  rdfs:label "Na h-Eileanan Siar" ;
  .

statistical-geography:S12000023 a skos:Concept ;
  skos:broader city-region:scottish-island-councils ;
  rdfs:label "Orkney Islands" ;
  .

statistical-geography:S12000027 a skos:Concept ;
  skos:broader city-region:scottish-island-councils ;
  rdfs:label "Shetland Islands" ;
  .
```

Something for a DM to think about.

**Comment by rossbowen** [comment]
https://github.com/GSS-Cogs/family-trade/issues/24 has City Regions too. Would be good to harmonise.

**Comment by robons** [comment]
Right, the data has been uploaded to PMD4 now and is accessible at 

However, I should note that I ran this dataset through my pivoted viewer and I'm not too happy with how the data is structured. I think each of the rows in the following screenshot should be measures so that all of the values for Belfast in 2018 show up on the same line.

![image](https://user-images.githubusercontent.com/73846016/112501147-e6a78280-8d80-11eb-81da-afe5f0e6e0ab.png)

How much do we care about the structure of the data at this point? Are we just happy enough that it's sort of on these even if the format is less than ideal?

**Comment by JasonHowell** [comment]
Close as it's been published to the Beta site.
