### ISSUE TITLE
ONS-International-trade-in-services-by-subnational-areas-of-the-UK

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#84]
https://github.com/GSS-Cogs/family-trade/tree/master/datasets/ONS-International-trade-in-services-by-subnational-areas-of-the-UK

**Comment by LPerryman** [comment]
All looks good to me.

**Comment by RedWalters** [comment]
Initial stage 2 transform done as per the spec
One thing to note, some of the location codes for scotland dont match up with what was specified in the spec and have been put in as such:
'Aberdeen City Region' : 'S12000033'
'Edinburgh and South East Scotland City Region' : 'S11000003'
'Glasgow City Region' : 'S12000049'
If these need changing to something else let me know and I can replace them

**Comment by robons** [comment]
I've fixed the failing tests and the dataset is now ready for review at https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-by-subnational-areas-of-the-uk-catalog-entry&filters-drawer=open

**Comment by Tracey-B** [comment]
BA comments:
The transform looks good to go, subject to the comments below:
Unable to filter by location and unable to view metadata as 'Server Error (500)' is returned when clicking the Identifier link in About.

**Comment by robons** [comment]
@rossbowen @ajtucker I could create a local codelist which unions together all of the NUTS codes with the ONS/Govt geographies which would enable users to filter. I would only do it locally to this dataset with `rdfs:seeAlso` predicates linking to the true NUTS and ONS/Govt geographies. It might be a bit of a pain to maintain.

What are your thoughts on that approach?

**Comment by rossbowen** [comment]
Can we create a local concept scheme which references the true URIs?

```turtle
<#scheme/location> a skos:ConceptScheme ;
  rdfs:label "A list of sub-national areas of the UK for the reporting of Trade in Services" ;
  .

<http://data.europa.eu/nuts/code/UKM> a skos:Concept ;
  skos:inScheme <#scheme/location> ;
  .

<http://statistics.data.gov.uk/id/statistical-geography/S12000033> a skos:Concept ;
  skos:inScheme <#scheme/location> ;
  .

# etc. etc.
```

**Comment by robons** [comment]
So I've chased this down the rabbit hole a little bit and it is possible, but it'll require changes to the Jenkins pipeline to ensure the tests which ensure all Concepts have labels passes. We run the tests against a limited set of graphs and we're not currently looking/expecting Concepts inside ConceptSchemes to live in different graphs, so this will require a bit of an alteration.

Further to this, I've noticed that the NUTS ConceptScheme that we have has skos:prefLabel instead of the required rdfs:label, so I'll have to alter that build pipeline to augment the ConceptScheme with rdfs:labels to ensure that any dataset which directly uses the NUTS codes can pass the relevant tests.

**Comment by robons** [comment]
Right, after much work, I've published the dataset now. It isn't perfect, a number of labels don't correctly show against some location identifiers, but you're able to filter by the location.

Note that I've added a `NUTS` group and a `UK Government Statistical Geographies` group so that it's clear where the individual Concepts come from.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/73846016/105877465-f06a6f00-5ff7-11eb-9872-d3b948817208.png">
<img width="561" alt="image" src="https://user-images.githubusercontent.com/73846016/105877504-fbbd9a80-5ff7-11eb-90cc-a5d102a3c652.png">

@Tracey-B would you be able to review it again and confirm whether you're happy with it or not?

https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-by-subnational-areas-of-the-uk-catalog-entry&filters-drawer=open

**Comment by robons** [comment]
There are still some failing tests, mostly due to problems in areas where Swirrl is in control. I've sent them a message on slack to highlight these problems.
> Hi Swirrl people, I’ve got a couple of things to mention
5:23
We have a [test failing](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-International-trade-in-services-by-subnational-areas-of-the-UK/lastCompletedBuild/testReport/(root)/pmd4_concept-schemes/Concepts_Max_Of_One_Sort_Priority/) which claims that some `skos:Concept`s have 2 `ui:sortPriority` values, however, I can’t find multiple sort priorities for the first item the test is highlighting - [see this query](https://staging.gss-data.org.uk/tools/sparql?query=PREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX%20void%3A%20%3Chttp%3A%2F%2Frdfs.org%2Fns%2Fvoid%23%3E%0APREFIX%20pmdkos%3A%20%3Chttp%3A%2F%2Fpublishmydata.com%2Fdef%2Fpmdkos%2F%3E%0APREFIX%20dcterms%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20dcat%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX%20pmdui%3A%20%3Chttp%3A%2F%2Fpublishmydata.com%2Fdef%2Fpmdui%2F%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20markdown%3A%20%3Chttps%3A%2F%2Fwww.w3.org%2Fns%2Fiana%2Fmedia-types%2Ftext%2Fmarkdown%23%3E%0APREFIX%20qb%3A%20%3Chttp%3A%2F%2Fpurl.org%2Flinked-data%2Fcube%23%3E%0APREFIX%20skos%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX%20ui%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fui%23%3E%0A%0ASELECT%20*%0AWHERE%20%7B%0A%20%20%3Chttp%3A%2F%2Fdata.europa.eu%2Fnuts%2Fcode%2FUK%3E%20ui%3AsortPriority%20%3FsortPriority.%0A%7D%0ALIMIT%201000). Similarly [this test fails](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-International-trade-in-services-by-subnational-areas-of-the-UK/lastCompletedBuild/testReport/(root)/pmd4_concept-schemes/Concept_Exactly_One_Label__or_prefLabel_/) and I can’t find any duplicate labels. (edit, this is probably a good example of some of the problems we have where things are fine when published, but tests fail in the drafter).
Secondly, we have a test failing ([here](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-International-trade-in-services-by-subnational-areas-of-the-UK/lastCompletedBuild/testReport/(root)/pmd4_concept-schemes/Concept_Max_One_Notation/)) on our of our datasets which refers to a the government statistical geographies Codelist which I believe you maintain. Would it be possible to fix the issues that the tests are highlighting in the ConceptScheme? It would be nice not to have to ignore failing tests. I’ve also noticed that elsewhere I’ve had tests fail which highlight that some of the concepts are missing `rdfs:label` (see [here](https://staging.gss-data.org.uk/tools/sparql?query=PREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX%20void%3A%20%3Chttp%3A%2F%2Frdfs.org%2Fns%2Fvoid%23%3E%0APREFIX%20pmdkos%3A%20%3Chttp%3A%2F%2Fpublishmydata.com%2Fdef%2Fpmdkos%2F%3E%0APREFIX%20dcterms%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20dcat%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX%20pmdui%3A%20%3Chttp%3A%2F%2Fpublishmydata.com%2Fdef%2Fpmdui%2F%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20markdown%3A%20%3Chttps%3A%2F%2Fwww.w3.org%2Fns%2Fiana%2Fmedia-types%2Ftext%2Fmarkdown%23%3E%0APREFIX%20qb%3A%20%3Chttp%3A%2F%2Fpurl.org%2Flinked-data%2Fcube%23%3E%0APREFIX%20skos%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0APREFIX%20ui%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fui%23%3E%0A%0ASELECT%20*%0AWHERE%20%7B%0A%20%20VALUES%20(%3Fconcept)%20%7B%0A%20%20%09(%3Chttp%3A%2F%2Fstatistics.data.gov.uk%2Fid%2Fstatistical-geography%2FW42000001%3E)%0A%20%20%20%20(%3Chttp%3A%2F%2Fstatistics.data.gov.uk%2Fid%2Fstatistical-geography%2FW42000004%3E)%0A%20%20%20%20(%3Chttp%3A%2F%2Fstatistics.data.gov.uk%2Fid%2Fstatistical-geography%2FS11000003%3E)%0A%20%20%7D%0A%20%20%3Fconcept%20rdfs%3Alabel%20%3FconceptLabel.%0A%7D%0ALIMIT%201000) for examples).

**Comment by robons** [comment]
@Tracey-B we're got a problem with the recently published correction to the underlying publication. 

> We have corrected errors in Tables 1, 2, 3, 4, 5, 6, 7 and 9. The previous version included incorrect estimates of EU, Rest of the World and total. These have now been corrected. This happened because of a programming error in the production system. 

Unfortunately, some of the values in Tables 8 no longer agree with the values provided in Table 9. Could you get in contact with the data producer and get them to correct please?

I've attached a CSV file which details the inconsistent values in the hope that it'll help.


[InconsistentValues.xlsx](https://github.com/GSS-Cogs/family-trade/files/5927442/InconsistentValues.xlsx)

**Comment by mikeAdamss** [comment]
have updated scraper to get latest data but one of the selections is coming up blank (i.e the data has changed since this was written), needs DE corrections.

**Comment by Shannon95** [comment]
Ready for review here : https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-by-subnational-areas-of-the-uk-catalog-entry&apply-filters=true

**Comment by JasonHowell** [comment]
Closing as published to the BETA site.
