### ISSUE TITLE
ONS-Imports-of-services-by-country-by-modes-of-supply

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#88]

**Comment by LPerryman** [comment]
To be joined with ONS-Exports-of-services-by-country-by-modes-of-supply
https://github.com/GSS-Cogs/family-trade/issues/83

**Comment by Shannon95** [comment]
Note  joined with ONS-Exports-of-services-by-country-by-modes-of-supply
https://github.com/GSS-Cogs/family-trade/issues/83
Imports transformation is run inside the Exports main and joined together there. 

The transformation process of Imports is still detailed within its own main for reference. 

Stage one, two and join done, for now, the pipeline for ONS-Exports-of-services-by-country-by-modes-of-supply needs to be added to Jenkins in order to run.

**Comment by Tracey-B** [comment]
BA Comments:

There are a number of URLs in the direction column.
Unit of Measure should be GBP Million.
The usual caveats apply.

**Comment by Tracey-B** [comment]
URLs in the direction column appear to have been resolved and the Unit of Measure has been updated to GBP MIllion, subject to the usual caveats this data set can be published.

This dataset has been combined with Exports of services by country by modes of supply and I will apply the comments to Github issue #83 too.

**Comment by Shannon95** [comment]
After a conversation with @Tracey-B and updating spec with changes due to the new release, Happy that the above fixes have been actioned and subject the usual caveats this can be published.

**Comment by JasonHowell** [comment]
This is on the BETA site but joined with the exports publication.
